// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st1_fsm_0 = "1";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st2_fsm_1 = "10";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st3_fsm_2 = "100";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st4_fsm_3 = "1000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st5_fsm_4 = "10000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st6_fsm_5 = "100000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st22_fsm_21 = "1000000000000000000000";
const sc_lv<23> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_ST_st23_fsm_22 = "10000000000000000000000";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv1_1 = "1";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_1 = "1";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_4 = "100";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_5 = "101";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_9 = "1001";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_B = "1011";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_2 = "10";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_6 = "110";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_7 = "111";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_A = "1010";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_C = "1100";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_8 = "1000";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_D = "1101";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_3 = "11";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_E = "1110";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_F = "1111";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_14 = "10100";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_15 = "10101";
const sc_lv<1> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv1_0 = "0";
const sc_lv<9> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv9_0 = "000000000";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_16 = "10110";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_EB = "11101011";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_E6 = "11100110";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_121 = "100100001";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_C4 = "11000100";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_C1 = "11000001";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_A0 = "10100000";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_9A = "10011010";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_6F = "1101111";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_6B = "1101011";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_42 = "1000010";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_3D = "111101";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_17 = "10111";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_C = "1100";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_F4 = "11110100";
const sc_lv<64> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv64_124 = "100100100";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_10 = "10000";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_11 = "10001";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_12 = "10010";
const sc_lv<32> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv32_13 = "10011";
const sc_lv<9> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv9_124 = "100100100";
const sc_lv<9> acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::ap_const_lv9_1 = "1";

acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( exitcond_fu_460_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( exitcond_fu_460_p2 );

    SC_METHOD(thread_ap_sig_bdd_102);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_109);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_118);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_125);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_133);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_142);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_149);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_170);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_221);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_236);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_247);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_260);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_276);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_321);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_329);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_337);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_345);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_62);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_69);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_77);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_85);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_93);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_85 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_125 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_bdd_93 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_bdd_133 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_bdd_149 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_bdd_221 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_bdd_236 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_bdd_321 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_bdd_329 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_bdd_337 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_41 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_bdd_345 );

    SC_METHOD(thread_ap_sig_cseq_ST_st21_fsm_20);
    sensitive << ( ap_sig_bdd_247 );

    SC_METHOD(thread_ap_sig_cseq_ST_st22_fsm_21);
    sensitive << ( ap_sig_bdd_260 );

    SC_METHOD(thread_ap_sig_cseq_ST_st23_fsm_22);
    sensitive << ( ap_sig_bdd_276 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_62 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_102 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_170 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_69 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_77 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_109 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_118 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_142 );

    SC_METHOD(thread_exitcond_fu_460_p2);
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( j_reg_243 );

    SC_METHOD(thread_grp_fu_272_p2);
    sensitive << ( state_q0 );
    sensitive << ( reg_256 );

    SC_METHOD(thread_j_1_fu_466_p2);
    sensitive << ( j_reg_243 );

    SC_METHOD(thread_state_addr_11_gep_fu_172_p3);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );

    SC_METHOD(thread_state_addr_2_gep_fu_91_p3);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_state_addr_3_gep_fu_100_p3);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_state_addr_5_gep_fu_118_p3);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_state_addr_7_gep_fu_136_p3);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_state_addr_9_gep_fu_154_p3);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_state_address0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( state_addr_2_reg_533 );
    sensitive << ( state_addr_3_reg_538 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( state_addr_5_reg_558 );
    sensitive << ( state_addr_7_reg_584 );
    sensitive << ( state_addr_9_reg_599 );
    sensitive << ( state_addr_11_reg_624 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( exitcond_fu_460_p2 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( tmp_6_fu_472_p1 );
    sensitive << ( tmp_7_fu_518_p1 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_state_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( exitcond_fu_460_p2 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_state_d0);
    sensitive << ( state_q0 );
    sensitive << ( tmp_s_reg_563 );
    sensitive << ( x_assign_1_reg_568 );
    sensitive << ( tmp_3_reg_609 );
    sensitive << ( tmp_5_reg_634 );
    sensitive << ( z_assign_reg_655 );
    sensitive << ( y_assign_reg_660 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( exitcond_fu_460_p2 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( tmp_4_fu_511_p2 );

    SC_METHOD(thread_state_we0);
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( exitcond_fu_460_p2 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );

    SC_METHOD(thread_tmp10_fu_477_p2);
    sensitive << ( reg_268 );
    sensitive << ( tmp_5_reg_634 );

    SC_METHOD(thread_tmp11_fu_486_p2);
    sensitive << ( tmp12_fu_482_p2 );
    sensitive << ( tmp10_fu_477_p2 );

    SC_METHOD(thread_tmp12_fu_482_p2);
    sensitive << ( tmp_1_i_i_reg_675 );
    sensitive << ( tmp_2_i_i_reg_680 );

    SC_METHOD(thread_tmp13_fu_492_p2);
    sensitive << ( tmp_1_i_reg_690 );
    sensitive << ( tmp_2_i_reg_695 );

    SC_METHOD(thread_tmp14_cast_fu_507_p1);
    sensitive << ( tmp14_fu_501_p2 );

    SC_METHOD(thread_tmp14_fu_501_p2);
    sensitive << ( tmp13_fu_492_p2 );
    sensitive << ( tmp15_fu_496_p2 );

    SC_METHOD(thread_tmp15_fu_496_p2);
    sensitive << ( plaintextbit );

    SC_METHOD(thread_tmp2_fu_291_p2);
    sensitive << ( state_q0 );
    sensitive << ( reg_260 );

    SC_METHOD(thread_tmp3_fu_311_p2);
    sensitive << ( reg_256 );
    sensitive << ( reg_264 );

    SC_METHOD(thread_tmp4_fu_317_p2);
    sensitive << ( state_q0 );
    sensitive << ( reg_264 );

    SC_METHOD(thread_tmp6_fu_373_p2);
    sensitive << ( reg_256 );
    sensitive << ( reg_268 );

    SC_METHOD(thread_tmp7_fu_416_p2);
    sensitive << ( tmp_29_reg_614 );
    sensitive << ( tmp8_fu_410_p2 );

    SC_METHOD(thread_tmp8_fu_410_p2);
    sensitive << ( tmp_32_fu_389_p1 );
    sensitive << ( tmp_2_i_i_i_fu_404_p2 );

    SC_METHOD(thread_tmp9_fu_421_p2);
    sensitive << ( tmp_reg_629 );
    sensitive << ( tmp_1_i_i_i_fu_399_p2 );

    SC_METHOD(thread_tmp_1_i_fu_450_p2);
    sensitive << ( ca );
    sensitive << ( tmp_25_reg_553 );

    SC_METHOD(thread_tmp_1_i_i_fu_438_p2);
    sensitive << ( state_q0 );
    sensitive << ( tmp_i_i_2_fu_432_p2 );

    SC_METHOD(thread_tmp_1_i_i_i_fu_399_p2);
    sensitive << ( tmp_24_reg_528 );
    sensitive << ( tmp_i_i_i_fu_393_p2 );

    SC_METHOD(thread_tmp_24_fu_278_p1);
    sensitive << ( state_q0 );

    SC_METHOD(thread_tmp_25_fu_282_p1);
    sensitive << ( state_q0 );

    SC_METHOD(thread_tmp_26_fu_303_p1);
    sensitive << ( x_assign_1_fu_297_p2 );

    SC_METHOD(thread_tmp_27_fu_369_p1);
    sensitive << ( z_assign_fu_364_p2 );

    SC_METHOD(thread_tmp_28_fu_307_p1);
    sensitive << ( state_q0 );

    SC_METHOD(thread_tmp_29_fu_329_p1);
    sensitive << ( tmp_3_fu_323_p2 );

    SC_METHOD(thread_tmp_2_i_fu_455_p2);
    sensitive << ( cb );
    sensitive << ( tmp_i_i_reg_665 );

    SC_METHOD(thread_tmp_2_i_i_fu_444_p2);
    sensitive << ( reg_260 );
    sensitive << ( reg_264 );

    SC_METHOD(thread_tmp_2_i_i_i_fu_404_p2);
    sensitive << ( tmp_27_fu_369_p1 );
    sensitive << ( tmp_31_fu_385_p1 );

    SC_METHOD(thread_tmp_30_fu_333_p1);
    sensitive << ( state_q0 );

    SC_METHOD(thread_tmp_31_fu_385_p1);
    sensitive << ( y_assign_fu_379_p2 );

    SC_METHOD(thread_tmp_32_fu_389_p1);
    sensitive << ( state_q0 );

    SC_METHOD(thread_tmp_3_fu_323_p2);
    sensitive << ( reg_268 );
    sensitive << ( tmp4_fu_317_p2 );

    SC_METHOD(thread_tmp_4_fu_511_p2);
    sensitive << ( tmp14_cast_fu_507_p1 );
    sensitive << ( tmp11_fu_486_p2 );

    SC_METHOD(thread_tmp_4_i_i_i_fu_341_p2);
    sensitive << ( tmp_26_reg_573 );

    SC_METHOD(thread_tmp_5_fu_358_p2);
    sensitive << ( reg_264 );
    sensitive << ( grp_fu_272_p2 );

    SC_METHOD(thread_tmp_5_i_i_i_fu_346_p2);
    sensitive << ( tmp_30_fu_333_p1 );
    sensitive << ( tmp_4_i_i_i_fu_341_p2 );

    SC_METHOD(thread_tmp_6_fu_472_p1);
    sensitive << ( j_1_fu_466_p2 );

    SC_METHOD(thread_tmp_7_fu_518_p1);
    sensitive << ( j_reg_243 );

    SC_METHOD(thread_tmp_fu_352_p2);
    sensitive << ( tmp_i9_i_i_fu_337_p2 );
    sensitive << ( tmp_5_i_i_i_fu_346_p2 );

    SC_METHOD(thread_tmp_i9_i_i_fu_337_p2);
    sensitive << ( tmp_26_reg_573 );
    sensitive << ( tmp_28_reg_594 );

    SC_METHOD(thread_tmp_i_i_2_fu_432_p2);
    sensitive << ( reg_260 );
    sensitive << ( reg_264 );

    SC_METHOD(thread_tmp_i_i_fu_426_p2);
    sensitive << ( tmp9_fu_421_p2 );
    sensitive << ( tmp7_fu_416_p2 );

    SC_METHOD(thread_tmp_i_i_i_fu_393_p2);
    sensitive << ( tmp_27_fu_369_p1 );
    sensitive << ( tmp_31_fu_385_p1 );

    SC_METHOD(thread_tmp_s_fu_286_p2);
    sensitive << ( reg_260 );
    sensitive << ( tmp1_reg_543 );

    SC_METHOD(thread_x_assign_1_fu_297_p2);
    sensitive << ( reg_256 );
    sensitive << ( tmp2_fu_291_p2 );

    SC_METHOD(thread_y_assign_fu_379_p2);
    sensitive << ( reg_264 );
    sensitive << ( tmp6_fu_373_p2 );

    SC_METHOD(thread_z_assign_fu_364_p2);
    sensitive << ( reg_260 );
    sensitive << ( tmp3_reg_604 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_460_p2 );

    ap_CS_fsm = "00000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, state_address0, "(port)state_address0");
    sc_trace(mVcdFile, state_ce0, "(port)state_ce0");
    sc_trace(mVcdFile, state_we0, "(port)state_we0");
    sc_trace(mVcdFile, state_d0, "(port)state_d0");
    sc_trace(mVcdFile, state_q0, "(port)state_q0");
    sc_trace(mVcdFile, plaintextbit, "(port)plaintextbit");
    sc_trace(mVcdFile, ca, "(port)ca");
    sc_trace(mVcdFile, cb, "(port)cb");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_41, "ap_sig_bdd_41");
    sc_trace(mVcdFile, reg_256, "reg_256");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_62, "ap_sig_bdd_62");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_69, "ap_sig_bdd_69");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_77, "ap_sig_bdd_77");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_85, "ap_sig_bdd_85");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_bdd_93, "ap_sig_bdd_93");
    sc_trace(mVcdFile, reg_260, "reg_260");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_102, "ap_sig_bdd_102");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_109, "ap_sig_bdd_109");
    sc_trace(mVcdFile, reg_264, "reg_264");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_118, "ap_sig_bdd_118");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_125, "ap_sig_bdd_125");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_bdd_133, "ap_sig_bdd_133");
    sc_trace(mVcdFile, reg_268, "reg_268");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_142, "ap_sig_bdd_142");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_bdd_149, "ap_sig_bdd_149");
    sc_trace(mVcdFile, tmp_24_fu_278_p1, "tmp_24_fu_278_p1");
    sc_trace(mVcdFile, tmp_24_reg_528, "tmp_24_reg_528");
    sc_trace(mVcdFile, state_addr_2_gep_fu_91_p3, "state_addr_2_gep_fu_91_p3");
    sc_trace(mVcdFile, state_addr_2_reg_533, "state_addr_2_reg_533");
    sc_trace(mVcdFile, state_addr_3_gep_fu_100_p3, "state_addr_3_gep_fu_100_p3");
    sc_trace(mVcdFile, state_addr_3_reg_538, "state_addr_3_reg_538");
    sc_trace(mVcdFile, grp_fu_272_p2, "grp_fu_272_p2");
    sc_trace(mVcdFile, tmp1_reg_543, "tmp1_reg_543");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_170, "ap_sig_bdd_170");
    sc_trace(mVcdFile, tmp_25_fu_282_p1, "tmp_25_fu_282_p1");
    sc_trace(mVcdFile, tmp_25_reg_553, "tmp_25_reg_553");
    sc_trace(mVcdFile, state_addr_5_gep_fu_118_p3, "state_addr_5_gep_fu_118_p3");
    sc_trace(mVcdFile, state_addr_5_reg_558, "state_addr_5_reg_558");
    sc_trace(mVcdFile, tmp_s_fu_286_p2, "tmp_s_fu_286_p2");
    sc_trace(mVcdFile, tmp_s_reg_563, "tmp_s_reg_563");
    sc_trace(mVcdFile, x_assign_1_fu_297_p2, "x_assign_1_fu_297_p2");
    sc_trace(mVcdFile, x_assign_1_reg_568, "x_assign_1_reg_568");
    sc_trace(mVcdFile, tmp_26_fu_303_p1, "tmp_26_fu_303_p1");
    sc_trace(mVcdFile, tmp_26_reg_573, "tmp_26_reg_573");
    sc_trace(mVcdFile, state_addr_7_gep_fu_136_p3, "state_addr_7_gep_fu_136_p3");
    sc_trace(mVcdFile, state_addr_7_reg_584, "state_addr_7_reg_584");
    sc_trace(mVcdFile, tmp_28_fu_307_p1, "tmp_28_fu_307_p1");
    sc_trace(mVcdFile, tmp_28_reg_594, "tmp_28_reg_594");
    sc_trace(mVcdFile, state_addr_9_gep_fu_154_p3, "state_addr_9_gep_fu_154_p3");
    sc_trace(mVcdFile, state_addr_9_reg_599, "state_addr_9_reg_599");
    sc_trace(mVcdFile, tmp3_fu_311_p2, "tmp3_fu_311_p2");
    sc_trace(mVcdFile, tmp3_reg_604, "tmp3_reg_604");
    sc_trace(mVcdFile, tmp_3_fu_323_p2, "tmp_3_fu_323_p2");
    sc_trace(mVcdFile, tmp_3_reg_609, "tmp_3_reg_609");
    sc_trace(mVcdFile, tmp_29_fu_329_p1, "tmp_29_fu_329_p1");
    sc_trace(mVcdFile, tmp_29_reg_614, "tmp_29_reg_614");
    sc_trace(mVcdFile, state_addr_11_gep_fu_172_p3, "state_addr_11_gep_fu_172_p3");
    sc_trace(mVcdFile, state_addr_11_reg_624, "state_addr_11_reg_624");
    sc_trace(mVcdFile, tmp_fu_352_p2, "tmp_fu_352_p2");
    sc_trace(mVcdFile, tmp_reg_629, "tmp_reg_629");
    sc_trace(mVcdFile, tmp_5_fu_358_p2, "tmp_5_fu_358_p2");
    sc_trace(mVcdFile, tmp_5_reg_634, "tmp_5_reg_634");
    sc_trace(mVcdFile, z_assign_fu_364_p2, "z_assign_fu_364_p2");
    sc_trace(mVcdFile, z_assign_reg_655, "z_assign_reg_655");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_bdd_221, "ap_sig_bdd_221");
    sc_trace(mVcdFile, y_assign_fu_379_p2, "y_assign_fu_379_p2");
    sc_trace(mVcdFile, y_assign_reg_660, "y_assign_reg_660");
    sc_trace(mVcdFile, tmp_i_i_fu_426_p2, "tmp_i_i_fu_426_p2");
    sc_trace(mVcdFile, tmp_i_i_reg_665, "tmp_i_i_reg_665");
    sc_trace(mVcdFile, tmp_1_i_i_fu_438_p2, "tmp_1_i_i_fu_438_p2");
    sc_trace(mVcdFile, tmp_1_i_i_reg_675, "tmp_1_i_i_reg_675");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_bdd_236, "ap_sig_bdd_236");
    sc_trace(mVcdFile, tmp_2_i_i_fu_444_p2, "tmp_2_i_i_fu_444_p2");
    sc_trace(mVcdFile, tmp_2_i_i_reg_680, "tmp_2_i_i_reg_680");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st21_fsm_20, "ap_sig_cseq_ST_st21_fsm_20");
    sc_trace(mVcdFile, ap_sig_bdd_247, "ap_sig_bdd_247");
    sc_trace(mVcdFile, tmp_1_i_fu_450_p2, "tmp_1_i_fu_450_p2");
    sc_trace(mVcdFile, tmp_1_i_reg_690, "tmp_1_i_reg_690");
    sc_trace(mVcdFile, tmp_2_i_fu_455_p2, "tmp_2_i_fu_455_p2");
    sc_trace(mVcdFile, tmp_2_i_reg_695, "tmp_2_i_reg_695");
    sc_trace(mVcdFile, j_1_fu_466_p2, "j_1_fu_466_p2");
    sc_trace(mVcdFile, j_1_reg_703, "j_1_reg_703");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st22_fsm_21, "ap_sig_cseq_ST_st22_fsm_21");
    sc_trace(mVcdFile, ap_sig_bdd_260, "ap_sig_bdd_260");
    sc_trace(mVcdFile, exitcond_fu_460_p2, "exitcond_fu_460_p2");
    sc_trace(mVcdFile, j_reg_243, "j_reg_243");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st23_fsm_22, "ap_sig_cseq_ST_st23_fsm_22");
    sc_trace(mVcdFile, ap_sig_bdd_276, "ap_sig_bdd_276");
    sc_trace(mVcdFile, tmp_6_fu_472_p1, "tmp_6_fu_472_p1");
    sc_trace(mVcdFile, tmp_7_fu_518_p1, "tmp_7_fu_518_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_bdd_321, "ap_sig_bdd_321");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_bdd_329, "ap_sig_bdd_329");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_bdd_337, "ap_sig_bdd_337");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_bdd_345, "ap_sig_bdd_345");
    sc_trace(mVcdFile, tmp_4_fu_511_p2, "tmp_4_fu_511_p2");
    sc_trace(mVcdFile, tmp2_fu_291_p2, "tmp2_fu_291_p2");
    sc_trace(mVcdFile, tmp4_fu_317_p2, "tmp4_fu_317_p2");
    sc_trace(mVcdFile, tmp_30_fu_333_p1, "tmp_30_fu_333_p1");
    sc_trace(mVcdFile, tmp_4_i_i_i_fu_341_p2, "tmp_4_i_i_i_fu_341_p2");
    sc_trace(mVcdFile, tmp_i9_i_i_fu_337_p2, "tmp_i9_i_i_fu_337_p2");
    sc_trace(mVcdFile, tmp_5_i_i_i_fu_346_p2, "tmp_5_i_i_i_fu_346_p2");
    sc_trace(mVcdFile, tmp6_fu_373_p2, "tmp6_fu_373_p2");
    sc_trace(mVcdFile, tmp_27_fu_369_p1, "tmp_27_fu_369_p1");
    sc_trace(mVcdFile, tmp_31_fu_385_p1, "tmp_31_fu_385_p1");
    sc_trace(mVcdFile, tmp_i_i_i_fu_393_p2, "tmp_i_i_i_fu_393_p2");
    sc_trace(mVcdFile, tmp_32_fu_389_p1, "tmp_32_fu_389_p1");
    sc_trace(mVcdFile, tmp_2_i_i_i_fu_404_p2, "tmp_2_i_i_i_fu_404_p2");
    sc_trace(mVcdFile, tmp8_fu_410_p2, "tmp8_fu_410_p2");
    sc_trace(mVcdFile, tmp_1_i_i_i_fu_399_p2, "tmp_1_i_i_i_fu_399_p2");
    sc_trace(mVcdFile, tmp9_fu_421_p2, "tmp9_fu_421_p2");
    sc_trace(mVcdFile, tmp7_fu_416_p2, "tmp7_fu_416_p2");
    sc_trace(mVcdFile, tmp_i_i_2_fu_432_p2, "tmp_i_i_2_fu_432_p2");
    sc_trace(mVcdFile, tmp12_fu_482_p2, "tmp12_fu_482_p2");
    sc_trace(mVcdFile, tmp10_fu_477_p2, "tmp10_fu_477_p2");
    sc_trace(mVcdFile, tmp13_fu_492_p2, "tmp13_fu_492_p2");
    sc_trace(mVcdFile, tmp15_fu_496_p2, "tmp15_fu_496_p2");
    sc_trace(mVcdFile, tmp14_fu_501_p2, "tmp14_fu_501_p2");
    sc_trace(mVcdFile, tmp14_cast_fu_507_p1, "tmp14_cast_fu_507_p1");
    sc_trace(mVcdFile, tmp11_fu_486_p2, "tmp11_fu_486_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::~acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        j_reg_243 = j_1_reg_703.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        j_reg_243 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        j_1_reg_703 = j_1_fu_466_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()))) {
        reg_256 = state_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()))) {
        reg_260 = state_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()))) {
        reg_264 = state_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        reg_268 = state_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        state_addr_11_reg_624 = state_addr_11_gep_fu_172_p3.read();
        tmp_reg_629 = tmp_fu_352_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        state_addr_2_reg_533 = state_addr_2_gep_fu_91_p3.read();
        tmp_24_reg_528 = tmp_24_fu_278_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        state_addr_3_reg_538 = state_addr_3_gep_fu_100_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        state_addr_5_reg_558 = state_addr_5_gep_fu_118_p3.read();
        tmp_25_reg_553 = tmp_25_fu_282_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        state_addr_7_reg_584 = state_addr_7_gep_fu_136_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        state_addr_9_reg_599 = state_addr_9_gep_fu_154_p3.read();
        tmp_28_reg_594 = tmp_28_fu_307_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        tmp1_reg_543 = grp_fu_272_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        tmp3_reg_604 = tmp3_fu_311_p2.read();
        tmp_29_reg_614 = tmp_29_fu_329_p1.read();
        tmp_3_reg_609 = tmp_3_fu_323_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        tmp_1_i_i_reg_675 = tmp_1_i_i_fu_438_p2.read();
        tmp_2_i_i_reg_680 = tmp_2_i_i_fu_444_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        tmp_1_i_reg_690 = tmp_1_i_fu_450_p2.read();
        tmp_2_i_reg_695 = tmp_2_i_fu_455_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        tmp_26_reg_573 = tmp_26_fu_303_p1.read();
        tmp_s_reg_563 = tmp_s_fu_286_p2.read();
        x_assign_1_reg_568 = x_assign_1_fu_297_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        tmp_5_reg_634 = tmp_5_fu_358_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        tmp_i_i_reg_665 = tmp_i_i_fu_426_p2.read();
        y_assign_reg_660 = y_assign_fu_379_p2.read();
        z_assign_reg_655 = z_assign_fu_364_p2.read();
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) && 
          !esl_seteq<1,1,1>(exitcond_fu_460_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) && 
         !esl_seteq<1,1,1>(exitcond_fu_460_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_102() {
    ap_sig_bdd_102 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_109() {
    ap_sig_bdd_109 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_118() {
    ap_sig_bdd_118 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_125() {
    ap_sig_bdd_125 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_133() {
    ap_sig_bdd_133 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_142() {
    ap_sig_bdd_142 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_149() {
    ap_sig_bdd_149 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_170() {
    ap_sig_bdd_170 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_221() {
    ap_sig_bdd_221 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_236() {
    ap_sig_bdd_236 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_247() {
    ap_sig_bdd_247 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(20, 20));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_260() {
    ap_sig_bdd_260 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(21, 21));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_276() {
    ap_sig_bdd_276 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(22, 22));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_321() {
    ap_sig_bdd_321 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_329() {
    ap_sig_bdd_329 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_337() {
    ap_sig_bdd_337 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_345() {
    ap_sig_bdd_345 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_41() {
    ap_sig_bdd_41 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_62() {
    ap_sig_bdd_62 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_69() {
    ap_sig_bdd_69 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_77() {
    ap_sig_bdd_77 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_85() {
    ap_sig_bdd_85 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_bdd_93() {
    ap_sig_bdd_93 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_85.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_125.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_bdd_93.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_bdd_133.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_bdd_149.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_bdd_221.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_bdd_236.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_bdd_321.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_bdd_329.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_bdd_337.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_41.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_bdd_345.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st21_fsm_20() {
    if (ap_sig_bdd_247.read()) {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st22_fsm_21() {
    if (ap_sig_bdd_260.read()) {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st23_fsm_22() {
    if (ap_sig_bdd_276.read()) {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_62.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_102.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_170.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_69.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_77.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_109.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_118.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_142.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_exitcond_fu_460_p2() {
    exitcond_fu_460_p2 = (!j_reg_243.read().is_01() || !ap_const_lv9_124.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_243.read() == ap_const_lv9_124);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_grp_fu_272_p2() {
    grp_fu_272_p2 = (reg_256.read() ^ state_q0.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_j_1_fu_466_p2() {
    j_1_fu_466_p2 = (!j_reg_243.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(j_reg_243.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_state_addr_11_gep_fu_172_p3() {
    state_addr_11_gep_fu_172_p3 =  (sc_lv<9>) (ap_const_lv64_3D);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_state_addr_2_gep_fu_91_p3() {
    state_addr_2_gep_fu_91_p3 =  (sc_lv<9>) (ap_const_lv64_E6);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_state_addr_3_gep_fu_100_p3() {
    state_addr_3_gep_fu_100_p3 =  (sc_lv<9>) (ap_const_lv64_121);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_state_addr_5_gep_fu_118_p3() {
    state_addr_5_gep_fu_118_p3 =  (sc_lv<9>) (ap_const_lv64_C1);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_state_addr_7_gep_fu_136_p3() {
    state_addr_7_gep_fu_136_p3 =  (sc_lv<9>) (ap_const_lv64_9A);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_state_addr_9_gep_fu_154_p3() {
    state_addr_9_gep_fu_154_p3 =  (sc_lv<9>) (ap_const_lv64_6B);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_state_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        state_address0 =  (sc_lv<9>) (tmp_7_fu_518_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) && 
                !esl_seteq<1,1,1>(exitcond_fu_460_p2.read(), ap_const_lv1_0))) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_124);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        state_address0 = state_addr_11_reg_624.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        state_address0 = state_addr_9_reg_599.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        state_address0 = state_addr_7_reg_584.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        state_address0 = state_addr_5_reg_558.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        state_address0 = state_addr_2_reg_533.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        state_address0 = state_addr_3_reg_538.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) && 
                esl_seteq<1,1,1>(exitcond_fu_460_p2.read(), ap_const_lv1_0))) {
        state_address0 =  (sc_lv<9>) (tmp_6_fu_472_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_F4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_17);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_3D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_42);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_6B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_6F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_9A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_A0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_C1);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_C4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_121);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_E6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        state_address0 =  (sc_lv<9>) (ap_const_lv64_EB);
    } else {
        state_address0 = "XXXXXXXXX";
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_state_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) && 
          esl_seteq<1,1,1>(exitcond_fu_460_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) && 
          !esl_seteq<1,1,1>(exitcond_fu_460_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
        state_ce0 = ap_const_logic_1;
    } else {
        state_ce0 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_state_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        state_d0 = state_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) && 
                !esl_seteq<1,1,1>(exitcond_fu_460_p2.read(), ap_const_lv1_0))) {
        state_d0 = tmp_4_fu_511_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        state_d0 = y_assign_reg_660.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        state_d0 = tmp_5_reg_634.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        state_d0 = tmp_3_reg_609.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        state_d0 = z_assign_reg_655.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        state_d0 = x_assign_1_reg_568.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        state_d0 = tmp_s_reg_563.read();
    } else {
        state_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_state_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) && 
          !esl_seteq<1,1,1>(exitcond_fu_460_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()))) {
        state_we0 = ap_const_logic_1;
    } else {
        state_we0 = ap_const_logic_0;
    }
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp10_fu_477_p2() {
    tmp10_fu_477_p2 = (reg_268.read() ^ tmp_5_reg_634.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp11_fu_486_p2() {
    tmp11_fu_486_p2 = (tmp12_fu_482_p2.read() ^ tmp10_fu_477_p2.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp12_fu_482_p2() {
    tmp12_fu_482_p2 = (tmp_2_i_i_reg_680.read() ^ tmp_1_i_i_reg_675.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp13_fu_492_p2() {
    tmp13_fu_492_p2 = (tmp_1_i_reg_690.read() ^ tmp_2_i_reg_695.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp14_cast_fu_507_p1() {
    tmp14_cast_fu_507_p1 = esl_zext<8,1>(tmp14_fu_501_p2.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp14_fu_501_p2() {
    tmp14_fu_501_p2 = (tmp13_fu_492_p2.read() ^ tmp15_fu_496_p2.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp15_fu_496_p2() {
    tmp15_fu_496_p2 = (plaintextbit.read() ^ ap_const_lv1_1);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp2_fu_291_p2() {
    tmp2_fu_291_p2 = (reg_260.read() ^ state_q0.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp3_fu_311_p2() {
    tmp3_fu_311_p2 = (reg_256.read() ^ reg_264.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp4_fu_317_p2() {
    tmp4_fu_317_p2 = (reg_264.read() ^ state_q0.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp6_fu_373_p2() {
    tmp6_fu_373_p2 = (reg_256.read() ^ reg_268.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp7_fu_416_p2() {
    tmp7_fu_416_p2 = (tmp8_fu_410_p2.read() ^ tmp_29_reg_614.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp8_fu_410_p2() {
    tmp8_fu_410_p2 = (tmp_32_fu_389_p1.read() ^ tmp_2_i_i_i_fu_404_p2.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp9_fu_421_p2() {
    tmp9_fu_421_p2 = (tmp_reg_629.read() ^ tmp_1_i_i_i_fu_399_p2.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_1_i_fu_450_p2() {
    tmp_1_i_fu_450_p2 = (tmp_25_reg_553.read() & ca.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_1_i_i_fu_438_p2() {
    tmp_1_i_i_fu_438_p2 = (tmp_i_i_2_fu_432_p2.read() & state_q0.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_1_i_i_i_fu_399_p2() {
    tmp_1_i_i_i_fu_399_p2 = (tmp_i_i_i_fu_393_p2.read() & tmp_24_reg_528.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_24_fu_278_p1() {
    tmp_24_fu_278_p1 = state_q0.read().range(1-1, 0);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_25_fu_282_p1() {
    tmp_25_fu_282_p1 = state_q0.read().range(1-1, 0);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_26_fu_303_p1() {
    tmp_26_fu_303_p1 = x_assign_1_fu_297_p2.read().range(1-1, 0);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_27_fu_369_p1() {
    tmp_27_fu_369_p1 = z_assign_fu_364_p2.read().range(1-1, 0);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_28_fu_307_p1() {
    tmp_28_fu_307_p1 = state_q0.read().range(1-1, 0);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_29_fu_329_p1() {
    tmp_29_fu_329_p1 = tmp_3_fu_323_p2.read().range(1-1, 0);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_2_i_fu_455_p2() {
    tmp_2_i_fu_455_p2 = (tmp_i_i_reg_665.read() & cb.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_2_i_i_fu_444_p2() {
    tmp_2_i_i_fu_444_p2 = (reg_260.read() & reg_264.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_2_i_i_i_fu_404_p2() {
    tmp_2_i_i_i_fu_404_p2 = (tmp_27_fu_369_p1.read() & tmp_31_fu_385_p1.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_30_fu_333_p1() {
    tmp_30_fu_333_p1 = state_q0.read().range(1-1, 0);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_31_fu_385_p1() {
    tmp_31_fu_385_p1 = y_assign_fu_379_p2.read().range(1-1, 0);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_32_fu_389_p1() {
    tmp_32_fu_389_p1 = state_q0.read().range(1-1, 0);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_3_fu_323_p2() {
    tmp_3_fu_323_p2 = (tmp4_fu_317_p2.read() ^ reg_268.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_4_fu_511_p2() {
    tmp_4_fu_511_p2 = (tmp14_cast_fu_507_p1.read() ^ tmp11_fu_486_p2.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_4_i_i_i_fu_341_p2() {
    tmp_4_i_i_i_fu_341_p2 = (tmp_26_reg_573.read() ^ ap_const_lv1_1);
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_5_fu_358_p2() {
    tmp_5_fu_358_p2 = (grp_fu_272_p2.read() ^ reg_264.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_5_i_i_i_fu_346_p2() {
    tmp_5_i_i_i_fu_346_p2 = (tmp_30_fu_333_p1.read() & tmp_4_i_i_i_fu_341_p2.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_6_fu_472_p1() {
    tmp_6_fu_472_p1 = esl_zext<64,9>(j_1_fu_466_p2.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_7_fu_518_p1() {
    tmp_7_fu_518_p1 = esl_zext<64,9>(j_reg_243.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_fu_352_p2() {
    tmp_fu_352_p2 = (tmp_i9_i_i_fu_337_p2.read() ^ tmp_5_i_i_i_fu_346_p2.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_i9_i_i_fu_337_p2() {
    tmp_i9_i_i_fu_337_p2 = (tmp_28_reg_594.read() & tmp_26_reg_573.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_i_i_2_fu_432_p2() {
    tmp_i_i_2_fu_432_p2 = (reg_260.read() ^ reg_264.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_i_i_fu_426_p2() {
    tmp_i_i_fu_426_p2 = (tmp9_fu_421_p2.read() ^ tmp7_fu_416_p2.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_i_i_i_fu_393_p2() {
    tmp_i_i_i_fu_393_p2 = (tmp_27_fu_369_p1.read() ^ tmp_31_fu_385_p1.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_tmp_s_fu_286_p2() {
    tmp_s_fu_286_p2 = (tmp1_reg_543.read() ^ reg_260.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_x_assign_1_fu_297_p2() {
    x_assign_1_fu_297_p2 = (tmp2_fu_291_p2.read() ^ reg_256.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_y_assign_fu_379_p2() {
    y_assign_fu_379_p2 = (tmp6_fu_373_p2.read() ^ reg_264.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_z_assign_fu_364_p2() {
    z_assign_fu_364_p2 = (tmp3_reg_604.read() ^ reg_260.read());
}

void acorn128_enc_onebyte_Encrypt_StateUpdate128_1bit::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        case 2097152 : 
            if (!esl_seteq<1,1,1>(exitcond_fu_460_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st23_fsm_22;
            }
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<23>) ("XXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

